niLang: Add astl::expected & astl::optional ;
prenaux/niLang pull request #17
Opened 2022-07-19 20:46 UTC by prenaux

## niLang: Added STL/expected.h and the skeleton of a test case for it ;

## niLang: Add STL/optional.h and a corresponding test case ;

## niLang: astl::optional implemented as expected<T,nullopt> ;

## Formal Notes

This PR fixes:
*
*
*

## Description, Motivation and Context

Link to issue: Fixes ?
Link to reference doc: ?

## How Has This Been Tested?

Command line to run all the tests that I run locally:
```
ham Run_ci
```

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that cause existing functionality to change)
* [ ] Documentation (code docs, comments, or changes to the doc systems)
* [ ] Testing/Build (test coverage or the test/build subsystems themselves)
* [ ] Packaging (adds examples or modifies a release package)

2022-07-19 20:46 UTC, prenaux commented
Current dependencies on/for this PR:
* main
  * **PR #17** <a href="https://app.graphite.dev/github/pr/prenaux/niLang/17" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/prenaux/niLang/17?utm_source=stack-comment).

2022-09-02 14:23 UTC, Edensan requested changes
See inline comments

2022-09-03 01:17 UTC, prenaux commented on sources/niLang/src/API/niLang/Math/MathProb.h
> +  astl::non_null<tU32CVec*> r,
Because its not supposed to ever hold a reference to it. astl::non_null<T*> is equivalent to T*, Nonnull<T> is equivalent to Ptr<T>.

2022-09-03 01:17 UTC, prenaux commented on sources/niLang/src/API/niLang/Utils/CollectionImpl.h
> +      niAssert(niIsOK(apContainer));
Yes indeed, this should be astl::non_null<>. I've done only the minimum to make it compile with niNoUnsafePtr.

I created https://github.com/prenaux/niLang/issues/23 to keep track of this.

2022-09-04 16:02 UTC, prenaux commented
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/prenaux/niLang/17?utm_source=stack-comment).
<!-- SHOW_IN_GRAPHITE_UI -->

Job Reference: QrsxxOZ6CSlm51a9vKf7

2022-09-04 16:05 UTC, merged