niLang/niCurl: Added the possibility to override a fetch request from…
prenaux/niLang pull request #54
Opened 2023-02-20 04:04 UTC by JavierFerrerGomez

## Description, Motivation and Context
The web client needs the option to implement a JavaScript function that overrides the call of niCurl fetch function. It can basically intercept the call and override it with anything it wants. One use case is to connect to a Crypto wallet. This function can handle call the wallet API and only return when all the transactions have been finalized. From the point of view of the niCURL client this all happens transparently.

To have access to all the emscripten environment this function can be implemented in the post_js_0.js file. The function module path is: Module.niCURL.handleFetchOverride

Example:
```
handleFetchOverride: function () {
  console.log("Module.niCURL: handleFetchOverride");
  return `
      {
        "url": "http://example.com",
        "headers": {
          "Content-Type": "application/json",
          "Accept": "application/json"
        },
        "payload": {
          "status": "OK",
          "data": "this will be send back to client in cml format"
        }
      }`
}
```
This function would just generate a json reply and return it to the client.

See the file post_js_0.js of this PR for more details.

* Link to issue: https://github.com/reddoordigital/reddoor/issues/575

## How Has This Been Tested?

For Linux or MacOS:
```
cd niLang/sources/niCurl
. hat emscripten
./ham all
```
How to test:
```
cd $WORK
simple-http-server regular .
```
Now open a web browser and go to this URL:
```
http://localhost:8123/niLang/bin/web-js/Test_niCURL_ra.html?niCURL.TraceFetch=1```
```

For Windows. There is not emscripten, so you can test only the standard niCURL:
How to Build
```
cd niLang/sources/niCURL
. hat
./ham Run_Test_niCURL
```

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Demos or Packages (adds examples or modifies a release package)
* [ ] Documentation (code docs, comments, or changes to the doc systems)
* [ ] Testing/Build (test coverage or the test/build subsystems themselves)

2023-02-20 05:07 UTC, prenaux requested changes
See comments for details:
- The override to only hook some URLs. Maybe if it returns "undefined" it just uses the regular path.
- Please add test case in niCURL/tsrc.

2023-02-20 05:07 UTC, prenaux commented on sources/emscripten/post_js_0.js
> +    //             "data": "this will be send back to client in cml format"
what's cml? shouldnt this be json?

2023-02-20 05:07 UTC, prenaux commented on sources/niCURL/src/CURL.cpp
> +      niDebugFmt(("niCURL: Using emscripten fetch..."));
TRACE_FETCH instead of niDebugFmt?

2023-02-20 05:07 UTC, prenaux commented on sources/niCURL/src/CURL.cpp
> +    if (_hasFetchOverride) {
This should move to its own function for clarity. Probably better to have _FetchWithOverride and _FetchEmscripten.

2023-02-20 05:07 UTC, prenaux commented on sources/niCURL/src/CURL.cpp
> +/>)""");
Extra `/>`

2023-02-20 05:07 UTC, prenaux commented on sources/niCURL/src/CURL.cpp
> +        cString payload = cString(R"""(
We should return JSON for all web APIs.

2023-02-20 05:07 UTC, prenaux commented on sources/niCURL/src/CURL.cpp
> +      if (!retString.empty()) {
We need a way to indicate that we want the regular fetch because the override will only be for some URL.

2023-02-21 03:16 UTC, JavierFerrerGomez commented on sources/niCURL/src/CURL.cpp
> +      niDebugFmt(("niCURL: Using emscripten fetch..."));
Lapsus :P

2023-02-23 03:58 UTC, jamesrdd commented
In the `handleFetchOverride()` javascript function, we need to optionally override some API endpoints while skipping the override for other endpoints. In order to achieve this, I think `handleFetchOverride()` needs to receive the URL being fetched as a parameter so we can add this custom override behavior only when fetching specific URLs.

2023-02-23 08:36 UTC, prenaux approved these changes
Ideally rename the parameters before merging. See comments.

2023-02-23 08:36 UTC, prenaux commented on sources/emscripten/post_js_0.js
> +    //   handleFetchOverride: function (request_url) {
`request_url` -> `aRequestUrl`

2023-02-23 08:36 UTC, prenaux commented on sources/niCURL/tsrc/Test_Fetch.cpp
> +        handleFetchOverride: function (request_url) {
`request_url` -> `aRequestUrl`

2023-02-23 08:36 UTC, prenaux commented on sources/niCURL/tsrc/Test_Fetch.cpp
> +        handleFetchOverride: function (request_url) {
`request_url` -> `aRequestUrl`

2023-02-23 08:36 UTC, prenaux commented on sources/niCURL/tsrc/Test_Fetch.cpp
> +        handleFetchOverride: function (request_url) {
`request_url` -> `aRequestUrl`

2023-02-23 09:30 UTC, merged